{% set name = "stuf" %}
{% set version = "0.9.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 080a88b940ca844474c239cc7aab0c530187e637a9dc6df111a99e2955bb35db

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - parse >=1.6.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - stuf

about:
  home: https://bitbucket.org/lcrees/stuf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Normal, default, ordered, chained, restricted, counter, and frozen dictionaries with attribute-style access.

extra:
  recipe-maintainers:
    - npavlovikj
